2023-03-22 18:22:50.239 [info] Extension host with pid 415576 started
2023-03-22 18:22:50.322 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-03-22 18:22:50.323 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python'
2023-03-22 18:22:50.323 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
2023-03-22 18:22:50.323 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*'
2023-03-22 18:22:51.022 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-03-22 18:22:51.058 [info] Eager extensions activated
2023-03-22 18:22:51.082 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-03-22 18:22:51.082 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-03-22 18:22:52.062 [error] Error: Workspace not trusted
	at w.createActivatedEnvironment (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:81136)
	at /home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:102568
	at t.tracing (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:167362)
	at i.value (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:102548)
	at r.getPackageInformation (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:17:42479)
	at /home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:102568
	at t.tracing (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:167362)
	at i.value (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:7:102548)
	at r.trackInterpreterPackages (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:17:42115)
	at r.trackPackagesInternal (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:17:41928)
	at r.trackPackages (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:17:40496)
	at f.trackPackagesOfActiveInterpreter (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:2:893003)
	at async f.trackUponActivation (/home/i0xfce/.vscode-oss/extensions/ms-toolsai.jupyter-2022.10.110-universal/out/extension.node.js:2:892762)
2023-03-22 18:22:56.445 [warning] DiagnosticCollection with name 'python' does already exist.
2023-03-22 18:22:56.573 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'api', root cause: vscode.github
2023-03-22 18:22:56.639 [info] ExtensionService#_doActivateExtension ms-python.isort, startup: false, activationEvent: 'onLanguage:python'
2023-03-22 18:22:56.640 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2023-03-22 18:24:05.278 [info] Extension host terminating: renderer closed the socket
2023-03-22 18:24:05.292 [info] Extension host with pid 415576 exiting with code 0
